#Madlibs Game :)
adjective = input("Enter an Adjective")
adjective_two = input("Enter an Adjective")
type_of_bird = input("Enter a type of Bird")
room_in_a_house = input("Enter a room a house")
verb_past = input("Enter a past tense verb")
verb = input("Enter a verb")
relatives_name = input("Enter a relatives name")
noun = input("Enter a noun")
a_liquid = input("Enter a liquid")
verb_ing = input("Enter a verb ending in -ing")
part_of_body = input("Enter a body part")
plural_noun = input("Enter a plural noun")
verb_ing2 = input("Enter a verb ending in -ing")
noun_two = input("Enter a nounn")

print("It was a " + adjective + ", cold November day. I woke up to the " + adjective_two + " smell of " + type_of_bird + " roasting in the " + room_in_a_house + " downstairs. I " + verb_past + " down the stairs to see if I could help " + verb + " the dinner. My mom said, 'See if " + relatives_name + " needs a fresh " + noun + ".' So I carried a tray of glasses full of " + a_liquid + " into the " + verb_ing + " room. When I got there, I couldn't believe my " + part_of_body + "! There were " + plural_noun + verb_ing2 + " on the " + noun_two)